const objects=[
 {key:'pillar',name:'Lion Capital',period:'c. 250 BCE · Mauryan India',group:'ancient',year:'250 BCE',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Lion%20Capital%20of%20Ashoka.jpg?width=900',summary:'Power, law, and a polished stone surface made public.',description:'Four lions stand back-to-back above the wheel of dharma in one of the most recognized images of the subcontinent. The capital once crowned a column at Sarnath and later became a national emblem.',fact:'Material · polished sandstone\nSite · Sarnath, Uttar Pradesh'},
 {key:'stupa',name:'Great Stupa Gate',period:'c. 100 BCE · Sanchi',group:'ancient',year:'100 BCE',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Sanchi%20Stupa.jpg?width=900',summary:'Stone becomes a storybook of journeys, animals, and devotion.',description:'The gateways at Sanchi turn the approach to a reliquary into a densely carved procession. Jataka tales and symbols of the Buddha unfold across their beams without a single human portrait of him.',fact:'Material · carved sandstone\nTradition · Buddhist narrative art'},
 {key:'ajanta',name:'Ajanta Bodhisattva',period:'c. 550 CE · Vakataka period',group:'classical',year:'550 CE',image:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Bodhisattva_Padmapani%2C_Ajanta%2C_cave_1%2C_India.jpg/960px-Bodhisattva_Padmapani%2C_Ajanta%2C_cave_1%2C_India.jpg',summary:'Mineral pigment and a soft gaze survive in a cave wall.',description:'Ajanta’s painters built volume with a limited palette of earth colors and a confident, rhythmic line. This bodhisattva carries the visual grace of a courtly figure into a space made for contemplation.',fact:'Material · tempera on rock-cut plaster\nSite · Ajanta, Maharashtra'},
 {key:'kailasa',name:'Kailasa Temple',period:'c. 760 CE · Rashtrakuta India',group:'medieval',year:'760 CE',image:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Ellora_Caves%2C_India%2C_Kailasa_Temple.jpg/960px-Ellora_Caves%2C_India%2C_Kailasa_Temple.jpg',summary:'An entire mountain imagined, excavated, and left standing.',description:'Rather than assembling a temple block by block, its makers cut Kailasa downward from living basalt. The result is a complete architectural world of shrines, elephants, gods, and shadow.',fact:'Material · volcanic basalt\nSite · Ellora, Maharashtra'},
 {key:'textile',name:'Patola Double Ikat',period:'c. 1600 CE · Gujarat',group:'medieval',year:'1600 CE',image:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Antique_Patan_Patola_Double_Ikat_Trade_Textile_courtesy_Wovensouls_Collection%2C_Singapore.jpg/960px-Antique_Patan_Patola_Double_Ikat_Trade_Textile_courtesy_Wovensouls_Collection%2C_Singapore.jpg',summary:'A geometric pattern held together thread by thread.',description:'In double ikat, warp and weft are resist-dyed before weaving so the design aligns at the loom. Patola textiles carried extraordinary labor, color, and status across courts and trading ports.',fact:'Material · silk, natural dyes\nTradition · Patan weaving'},
 {key:'miniature',name:'Bani Thani',period:'c. 1775 CE · Kishangarh',group:'modern',year:'1775 CE',image:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/4_Radha_%28Bani_Thani%29%2C_Kishangarh%2C_ca._1750%2C_National_Museum_New_Delhi.jpg/960px-4_Radha_%28Bani_Thani%29%2C_Kishangarh%2C_ca._1750%2C_National_Museum_New_Delhi.jpg',summary:'A profile becomes an icon through line, elongation, and color.',description:'The celebrated Bani Thani type stretches the face into an elegant, almost musical silhouette. Kishangarh painters made courtly love and devotional poetry shimmer in jewel-like miniature scale.',fact:'Material · opaque watercolor on paper\nSchool · Kishangarh miniature painting'}
];
const feature=document.querySelector('.feature');
const years=document.querySelectorAll('.year');
const grid=document.querySelector('.object-grid');
const drawer=document.querySelector('#drawer');
function renderFeature(index){const item=objects[index];feature.innerHTML=`<img src="${item.image}" alt="${item.name}"><div class="feature-copy"><span class="index">${String(index+1).padStart(2,'0')} / ${item.year}</span><h3>${item.name}</h3><p>${item.description}</p><button class="read" type="button" data-open="${item.key}">Open field note →</button></div>`;years.forEach((year,i)=>{year.classList.toggle('active',i===index);year.setAttribute('aria-selected',i===index?'true':'false')});feature.querySelector('[data-open]').addEventListener('click',()=>openDrawer(item.key))}
function renderGrid(filter='all'){grid.innerHTML=objects.map(item=>`<article class="object" data-group="${item.group}"><img src="${item.image}" alt="${item.name}"><div><span class="period">${item.period}</span><h3>${item.name}</h3><p>${item.summary}</p><button class="read" type="button" data-open="${item.key}">Read the note →</button></div></article>`).join('');grid.querySelectorAll('.object').forEach(card=>{card.hidden=filter!=='all'&&card.dataset.group!==filter;card.querySelector('[data-open]').addEventListener('click',()=>openDrawer(card.querySelector('[data-open]').dataset.open))})}
function openDrawer(key){const item=objects.find(object=>object.key===key);document.querySelector('#drawer-image').src=item.image;document.querySelector('#drawer-image').alt=item.name;document.querySelector('#drawer-period').textContent=item.period;document.querySelector('#drawer-title').textContent=item.name;document.querySelector('#drawer-description').textContent=item.description;document.querySelector('#drawer-fact').textContent=item.fact;drawer.hidden=false;document.querySelector('.drawer-close').focus()}
function closeDrawer(){drawer.hidden=true}
years.forEach(year=>year.addEventListener('click',()=>renderFeature(Number(year.dataset.index))));document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');button.classList.add('active');renderGrid(button.dataset.filter)}));document.querySelector('.drawer-close').addEventListener('click',closeDrawer);drawer.addEventListener('click',event=>{if(event.target===drawer)closeDrawer()});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeDrawer()});renderFeature(0);renderGrid();
